# Data cleaning using Pandas and Python

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\chari\OneDrive\Desktop\Walmart Data Analysis Project\archive (1).zip', encoding_errors ='ignore')

In [3]:
df.shape

(10051, 11)

In [4]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [5]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [7]:
#Removing duplicates

df.duplicated().sum()

np.int64(51)

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df.shape

(10000, 11)

In [10]:
#Dropping all rows with missing values
df.dropna(inplace = True)

In [11]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [12]:
df.shape

(9969, 11)

In [13]:
df.dtypes

invoice_id          int64
Branch             object
City               object
category           object
unit_price         object
quantity          float64
date               object
time               object
payment_method     object
rating            float64
profit_margin     float64
dtype: object

In [14]:
#converting data types of unit-price 

df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 934.6+ KB

In [16]:
#New column to be added for total price = unit_price * quantity
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [17]:
df['Total_price'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,Total_price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17



# Data cleaning is done will be extracting it to MySQL
<br>
<br>

In [29]:
import sqlalchemy as sal

In [30]:
engine = sal.create_engine('mysql+pymysql://root:123456@localhost:3306/test')
conn= engine.connect()

In [31]:
df.to_sql(name = 'walmart_raw', con=conn, if_exists = 'append', index=False)

9969

In [32]:
df.columns = df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin',
       'total_price'],
      dtype='object')

 # Selecting all the data of the schema using MySQL
<br>

In [41]:
query = "SELECT * FROM walmart_raw"
df = pd.read_sql(query, engine)
df.head()

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

# Selcting the distinct payment methods
<br>

In [50]:
query = """

SELECT DISTINCT payment_method 
from walmart_raw

"""
df = pd.read_sql(query, engine)
df

  payment_method
0        Ewallet
1           Cash
2    Credit card

# Solving business problems
### Q.1 Find the different payment method and number of transaction, number of qty sold. ###

In [52]:
query = """

SELECT payment_method, COUNT(*) as no_payments, sum(quantity) as no_qty_sold
from walmart_raw
GROUP BY payment_method

"""

df = pd.read_sql(query, engine)
df

  payment_method  no_payments  no_qty_sold
0        Ewallet        11643      26796.0
1           Cash         5496      14952.0
2    Credit card        12768      28701.0

### Q.2 identify the highest-rated category in each branch, displaying the branch, category and Avg rating.

In [53]:
query = """

SELECT branch, category,  AVG(rating) as avg_rating,
RANK() OVER(PARTITION BY branch ORDER BY AVG(rating) DESC) as ranks
FrOM walmart_raw
GROUP BY 1, 2

"""
df = pd.read_sql(query, engine)
df

      branch                category  avg_rating  ranks
0    WALM001  Electronic accessories    7.450000      1
1    WALM001       Sports and travel    6.533333      2
2    WALM001     Fashion accessories    6.357576      3
3    WALM001      Home and lifestyle    6.163889      4
4    WALM002      Food and beverages    8.250000      1
..       ...                     ...         ...    ...
517  WALM100       Health and beauty    6.900000      1
518  WALM100       Sports and travel    6.333333      2
519  WALM100      Home and lifestyle    6.250000      3
520  WALM100  Electronic accessories    6.166667      4
521  WALM100     Fashion accessories    6.068000      5

[522 rows x 4 columns]

### Q.2.a Selecting only rank 1

In [54]:
query = """

SELECT  *
From 
(
	SELECT 
      branch, 
      category,  
      AVG(rating) as avg_rating,
      RANK() OVER(PARTITION BY branch ORDER BY AVG(rating) DESC) as ranks
      From walmart_raw
      GROUP BY 1, 2
) as ranked_data

WHERE ranks = 1

"""
df = pd.read_sql(query, engine)
df

      branch                category  avg_rating  ranks
0    WALM001  Electronic accessories    7.450000      1
1    WALM002      Food and beverages    8.250000      1
2    WALM003       Sports and travel    7.500000      1
3    WALM004      Food and beverages    9.300000      1
4    WALM005       Health and beauty    8.366667      1
..       ...                     ...         ...    ...
96   WALM096       Sports and travel    9.600000      1
97   WALM097      Food and beverages    7.675000      1
98   WALM098       Health and beauty    9.800000      1
99   WALM099  Electronic accessories    5.950000      1
100  WALM100       Health and beauty    6.900000      1

[101 rows x 4 columns]

### Q.3 Identfying the busiest day for each branch on the number of transaction.

In [60]:
query = """

SELECT *
FROM
(
SELECT branch,
dayname(str_to_date(date, '%%d/%%m/%%y')) as day,
COUNT(*) as no_transaction,
RANK() OVER(PARTITION by branch ORDER  BY COUNT(*) DESC) as ranks
FROM walmart_raw
GROUP BY 1, 2
) as ranks
WHERE ranks = 1

"""

df = pd.read_sql(query, engine)
df

      branch        day  no_transaction  ranks
0    WALM001   Thursday              48      1
1    WALM002   Thursday              45      1
2    WALM003    Tuesday              99      1
3    WALM004     Sunday              42      1
4    WALM005  Wednesday              57      1
..       ...        ...             ...    ...
109  WALM096    Tuesday              45      1
110  WALM097     Friday              36      1
111  WALM098     Monday              54      1
112  WALM099     Sunday              90      1
113  WALM100  Wednesday              42      1

[114 rows x 4 columns]

### Q.4 Calculate the total number of quantity items sold per payment method. List the payment method and total quantity.

In [61]:
query = """

SELECT payment_method, COUNT(*) as no_payments, sum(quantity) as no_qty_sold
from walmart_raw
GROUP BY payment_method

"""

df = pd.read_sql(query, engine)
df

  payment_method  no_payments  no_qty_sold
0        Ewallet        11643      26796.0
1           Cash         5496      14952.0
2    Credit card        12768      28701.0

###   Q.5 Determine the average, minimum, maximum rating of products for each city. List the city, avrage_rating, min_rating and max_rating.

In [62]:
query = """

SELECT city, category,
AVG(rating) as avrage_rating, min(rating) as min_rating, max(rating) as max_rating
from walmart_raw
GROUP BY 1, 2
ORDER BY 1, 3, 4, 5

"""

df = pd.read_sql(query, engine)
df

        city                category  avrage_rating  min_rating  max_rating
0    Abilene      Home and lifestyle       6.096875         4.0         9.0
1    Abilene     Fashion accessories       6.240625         4.0         9.0
2    Abilene      Food and beverages       6.950000         6.0         8.9
3    Abilene  Electronic accessories       7.966667         7.1         8.8
4    Abilene       Health and beauty       9.700000         9.7         9.7
..       ...                     ...            ...         ...         ...
508  Weslaco  Electronic accessories       5.078261         3.0         8.4
509  Weslaco      Home and lifestyle       5.183505         3.0         9.2
510  Weslaco       Sports and travel       5.600000         4.1         7.1
511  Weslaco       Health and beauty       6.750000         4.3         9.2
512  Weslaco      Food and beverages       8.733333         7.1         9.8

[513 rows x 5 columns]

### Q.6 Calculate the total profit for each category by considering total profit as (unit_price * quanity * profit_margin ) 
###     List the category and total_profit, ordered from highest to lowest profit.

In [63]:
query = """

SELECT category, sum(unit_price * quantity * profit_margin) as total_profit
FROM walmart_raw
GROUP BY 1
ORDER BY total_profit DESC

"""

df = pd.read_sql(query, engine)
df

                 category  total_profit
0     Fashion accessories   576944.6796
1      Home and lifestyle   576640.9143
2  Electronic accessories    92317.4685
3      Food and beverages    64658.5866
4       Sports and travel    61841.4246
5       Health and beauty    56015.2035

### Q.7 Determine the most common payment method for each branch. Display branch and the preffered_payment_method

In [64]:
query = """

WITH cte as 
(
SELECT branch, payment_method, COUNT(*) as no_payments,
RANK() OVER(PARTITION BY branch ORDER BY COUNT(*) DESC) as  ranks
from walmart_raw
GROUP BY 1, 2
)
SELECT *
FROM cte
where ranks = 1

"""


df = pd.read_sql(query, engine)
df

     branch payment_method  no_payments  ranks
0   WALM001        Ewallet          135      1
1   WALM002        Ewallet          111      1
2   WALM003    Credit card          345      1
3   WALM004        Ewallet          132      1
4   WALM005        Ewallet          168      1
..      ...            ...          ...    ...
95  WALM096        Ewallet          150      1
96  WALM097        Ewallet          114      1
97  WALM098        Ewallet          132      1
98  WALM099    Credit card          249      1
99  WALM100        Ewallet          126      1

[100 rows x 4 columns]

### Q.8 categorize sales into 3 groups MORNING, AFTERNOON, EVNING. FIND out which of the shift and number of invoice

In [65]:
query = """

SELECT  branch,  
CASE 
   WHEN extract(HOUR FROM time) < 12 THEN 'MORNING'
   WHEN EXTRACT(HOUR FROM time) BETWEEN 12 AND 17 THEN 'AFTERNOON'
   ELSE 'EVENING'
END as shift, COUNT(*)
FROM walmart_raw
GROUP BY 1, 2
ORDER BY 1, 3 DESC

"""

df = pd.read_sql(query, engine)
df

      branch      shift  COUNT(*)
0    WALM001  AFTERNOON       108
1    WALM001    EVENING        90
2    WALM001    MORNING        24
3    WALM002  AFTERNOON        87
4    WALM002    EVENING        63
..       ...        ...       ...
295  WALM099    MORNING       120
296  WALM099    EVENING        96
297  WALM100  AFTERNOON        72
298  WALM100    MORNING        57
299  WALM100    EVENING        57

[300 rows x 3 columns]

### Q.9  Identify the 5 branch with the highest decrease ratio in revenue compare to last year current year 2023 and last year 2022 
###      revenue decrease ratio as rdr = ((last year revnue - current year revenue) / last year revneue) * 100

In [67]:
query = """

WITH revenue_2022 AS
(
SELECT 
      branch, 
      sum(total_price) as revenue
from walmart_raw
WHERE year(str_to_date(date, '%%d/%%m/%%y')) = 2022
GROUP BY 1
),
revenue_2023 AS
(
SELECT 
      branch, 
      sum(total_price) as revenue
from walmart_raw
WHERE year(str_to_date(date, '%%d/%%m/%%y')) = 2023
GROUP BY 1
ORDER BY 1
)
SELECT ls.branch, ls.revenue as last_year_revenue, cs.revenue as current_year_revenue,
round((ls.revenue - cs.revenue)/ls.revenue * 100,2) as rdr
FROM revenue_2022 as ls
jOIN 
revenue_2023 as cs
ON ls.branch = cs.branch
WHERE ls.revenue > cs.revenue
ORDER BY 4 desc
LIMIT 5

"""

df = pd.read_sql(query, engine)
df

    branch  last_year_revenue  current_year_revenue    rdr
0  WALM045             5193.0                1941.0  62.62
1  WALM047             7743.0                3207.0  58.58
2  WALM098             7338.0                3090.0  57.89
3  WALM033             6297.0                2793.0  55.65
4  WALM081             5169.0                2550.0  50.67